# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_trigger_server/camera_trigger_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import mavsdk_options_pb2 as mavsdk__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_trigger_server/camera_trigger_server.proto',
  package='mavsdk.rpc.camera_trigger_server',
  syntax='proto3',
  serialized_options=b'\n\037io.mavsdk.camera_trigger_serverB\030CameraTriggerServerProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1camera_trigger_server/camera_trigger_server.proto\x12 mavsdk.rpc.camera_trigger_server\x1a\x14mavsdk_options.proto\"\x19\n\x17SubscribeCaptureRequest\"*\n\x0f\x43\x61ptureResponse\x12\x17\n\x0fsequence_number\x18\x01 \x01(\r2\xa7\x01\n\x1a\x43\x61meraTriggerServerService\x12\x88\x01\n\x10SubscribeCapture\x12\x39.mavsdk.rpc.camera_trigger_server.SubscribeCaptureRequest\x1a\x31.mavsdk.rpc.camera_trigger_server.CaptureResponse\"\x04\x80\xb5\x18\x00\x30\x01\x42;\n\x1fio.mavsdk.camera_trigger_serverB\x18\x43\x61meraTriggerServerProtob\x06proto3'
  ,
  dependencies=[mavsdk__options__pb2.DESCRIPTOR,])




_SUBSCRIBECAPTUREREQUEST = _descriptor.Descriptor(
  name='SubscribeCaptureRequest',
  full_name='mavsdk.rpc.camera_trigger_server.SubscribeCaptureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=134,
)


_CAPTURERESPONSE = _descriptor.Descriptor(
  name='CaptureResponse',
  full_name='mavsdk.rpc.camera_trigger_server.CaptureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='mavsdk.rpc.camera_trigger_server.CaptureResponse.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['SubscribeCaptureRequest'] = _SUBSCRIBECAPTUREREQUEST
DESCRIPTOR.message_types_by_name['CaptureResponse'] = _CAPTURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscribeCaptureRequest = _reflection.GeneratedProtocolMessageType('SubscribeCaptureRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBECAPTUREREQUEST,
  '__module__' : 'camera_trigger_server.camera_trigger_server_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.camera_trigger_server.SubscribeCaptureRequest)
  })
_sym_db.RegisterMessage(SubscribeCaptureRequest)

CaptureResponse = _reflection.GeneratedProtocolMessageType('CaptureResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAPTURERESPONSE,
  '__module__' : 'camera_trigger_server.camera_trigger_server_pb2'
  # @@protoc_insertion_point(class_scope:mavsdk.rpc.camera_trigger_server.CaptureResponse)
  })
_sym_db.RegisterMessage(CaptureResponse)


DESCRIPTOR._options = None

_CAMERATRIGGERSERVERSERVICE = _descriptor.ServiceDescriptor(
  name='CameraTriggerServerService',
  full_name='mavsdk.rpc.camera_trigger_server.CameraTriggerServerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=181,
  serialized_end=348,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeCapture',
    full_name='mavsdk.rpc.camera_trigger_server.CameraTriggerServerService.SubscribeCapture',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBECAPTUREREQUEST,
    output_type=_CAPTURERESPONSE,
    serialized_options=b'\200\265\030\000',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERATRIGGERSERVERSERVICE)

DESCRIPTOR.services_by_name['CameraTriggerServerService'] = _CAMERATRIGGERSERVERSERVICE

# @@protoc_insertion_point(module_scope)
